# whitelist
language: go
go: 
  - 1.7.4
branches:  
  only:
    - master
sudo: required
services:  
#Enable docker service inside travis
  - docker
  - postgresql
  - redis-server
env:
  - DATABASE_URL="postgres://postgres:@localhost:5432/travis_ci_test?sslmode=disable"
before_install:
  - sudo apt-get update
  - sudo apt-get install -yq python3
  - sudo apt-get install -yq r-base
  - go get golang.org/x/tools/cmd/cover
  - go get -t -v ./...
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - pip install --user jupyter_kernel_gateway
script:
  - make
  - docker --version  # document the version travis is using
  - pip install --user awscli # install aws cli w/o sudo
  - export PATH=$PATH:$HOME/.local/bin # put aws in the path
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  - slack: 3blades:WkvRG9pgF8jIOpq8i8BjRqy3
